//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class rf21xPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="SWIGRegisterExceptionCallbacks_rf21x")]
    public static extern void SWIGRegisterExceptionCallbacks_rf21x(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_rf21x")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_rf21x(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_rf21x(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_rf21x(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(rf21xPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(rf21xPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="SWIGRegisterStringCallback_rf21x")]
    public static extern void SWIGRegisterStringCallback_rf21x(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_rf21x(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static rf21xPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_Clear")]
  public static extern void RF21xMessageRawData_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_Add")]
  public static extern void RF21xMessageRawData_Add(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_size")]
  public static extern uint RF21xMessageRawData_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_capacity")]
  public static extern uint RF21xMessageRawData_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_reserve")]
  public static extern void RF21xMessageRawData_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_new_RF21xMessageRawData__SWIG_0")]
  public static extern global::System.IntPtr new_RF21xMessageRawData__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_new_RF21xMessageRawData__SWIG_1")]
  public static extern global::System.IntPtr new_RF21xMessageRawData__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_new_RF21xMessageRawData__SWIG_2")]
  public static extern global::System.IntPtr new_RF21xMessageRawData__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_getitemcopy")]
  public static extern byte RF21xMessageRawData_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_getitem")]
  public static extern byte RF21xMessageRawData_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_setitem")]
  public static extern void RF21xMessageRawData_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, byte jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_AddRange")]
  public static extern void RF21xMessageRawData_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_GetRange")]
  public static extern global::System.IntPtr RF21xMessageRawData_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_Insert")]
  public static extern void RF21xMessageRawData_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, byte jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_InsertRange")]
  public static extern void RF21xMessageRawData_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_RemoveAt")]
  public static extern void RF21xMessageRawData_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_RemoveRange")]
  public static extern void RF21xMessageRawData_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_Repeat")]
  public static extern global::System.IntPtr RF21xMessageRawData_Repeat(byte jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_Reverse__SWIG_0")]
  public static extern void RF21xMessageRawData_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_Reverse__SWIG_1")]
  public static extern void RF21xMessageRawData_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_SetRange")]
  public static extern void RF21xMessageRawData_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_Contains")]
  public static extern bool RF21xMessageRawData_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_IndexOf")]
  public static extern int RF21xMessageRawData_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_LastIndexOf")]
  public static extern int RF21xMessageRawData_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessageRawData_Remove")]
  public static extern bool RF21xMessageRawData_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_delete_RF21xMessageRawData")]
  public static extern void delete_RF21xMessageRawData(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_Clear")]
  public static extern void RF21xHidSerialNumbers_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_Add")]
  public static extern void RF21xHidSerialNumbers_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_size")]
  public static extern uint RF21xHidSerialNumbers_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_capacity")]
  public static extern uint RF21xHidSerialNumbers_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_reserve")]
  public static extern void RF21xHidSerialNumbers_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_new_RF21xHidSerialNumbers__SWIG_0")]
  public static extern global::System.IntPtr new_RF21xHidSerialNumbers__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_new_RF21xHidSerialNumbers__SWIG_1")]
  public static extern global::System.IntPtr new_RF21xHidSerialNumbers__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_new_RF21xHidSerialNumbers__SWIG_2")]
  public static extern global::System.IntPtr new_RF21xHidSerialNumbers__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_getitemcopy")]
  public static extern string RF21xHidSerialNumbers_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_getitem")]
  public static extern string RF21xHidSerialNumbers_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_setitem")]
  public static extern void RF21xHidSerialNumbers_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_AddRange")]
  public static extern void RF21xHidSerialNumbers_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_GetRange")]
  public static extern global::System.IntPtr RF21xHidSerialNumbers_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_Insert")]
  public static extern void RF21xHidSerialNumbers_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_InsertRange")]
  public static extern void RF21xHidSerialNumbers_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_RemoveAt")]
  public static extern void RF21xHidSerialNumbers_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_RemoveRange")]
  public static extern void RF21xHidSerialNumbers_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_Repeat")]
  public static extern global::System.IntPtr RF21xHidSerialNumbers_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_Reverse__SWIG_0")]
  public static extern void RF21xHidSerialNumbers_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_Reverse__SWIG_1")]
  public static extern void RF21xHidSerialNumbers_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_SetRange")]
  public static extern void RF21xHidSerialNumbers_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_Contains")]
  public static extern bool RF21xHidSerialNumbers_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_IndexOf")]
  public static extern int RF21xHidSerialNumbers_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_LastIndexOf")]
  public static extern int RF21xHidSerialNumbers_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xHidSerialNumbers_Remove")]
  public static extern bool RF21xHidSerialNumbers_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_delete_RF21xHidSerialNumbers")]
  public static extern void delete_RF21xHidSerialNumbers(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_DT_Unknow_get")]
  public static extern int RF21X_DT_Unknow_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_DT_RF217_get")]
  public static extern int RF21X_DT_RF217_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_DT_RF218_get")]
  public static extern int RF21X_DT_RF218_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_DT_RF219_get")]
  public static extern int RF21X_DT_RF219_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_DT_RF215_get")]
  public static extern int RF21X_DT_RF215_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_DT_RF228_get")]
  public static extern int RF21X_DT_RF228_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_Unknow_get")]
  public static extern int RF21X_MT_Unknow_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_Teacher_get")]
  public static extern int RF21X_MT_Teacher_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_Student_get")]
  public static extern int RF21X_MT_Student_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_SetId_get")]
  public static extern int RF21X_MT_SetId_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_Auth_get")]
  public static extern int RF21X_MT_Auth_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_RecSn_get")]
  public static extern int RF21X_MT_RecSn_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_RecVersion_get")]
  public static extern int RF21X_MT_RecVersion_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_RecString_get")]
  public static extern int RF21X_MT_RecString_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_RecChannel_get")]
  public static extern int RF21X_MT_RecChannel_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_RecPower_get")]
  public static extern int RF21X_MT_RecPower_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_AllQuResult_get")]
  public static extern int RF21X_MT_AllQuResult_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_MT_AllIdResult_get")]
  public static extern int RF21X_MT_AllIdResult_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Homewrok_get")]
  public static extern int RF21X_QT_Homewrok_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Unknow_get")]
  public static extern int RF21X_QT_Unknow_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Rush_get")]
  public static extern int RF21X_QT_Rush_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Single_get")]
  public static extern int RF21X_QT_Single_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Multiple_get")]
  public static extern int RF21X_QT_Multiple_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Number_get")]
  public static extern int RF21X_QT_Number_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Text_get")]
  public static extern int RF21X_QT_Text_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Classify_get")]
  public static extern int RF21X_QT_Classify_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Sort_get")]
  public static extern int RF21X_QT_Sort_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_Qt_JudgeOrVote_get")]
  public static extern int RF21X_Qt_JudgeOrVote_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_SelectId_get")]
  public static extern int RF21X_QT_SelectId_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Control_get")]
  public static extern int RF21X_QT_Control_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_SelfPaced_get")]
  public static extern int RF21X_QT_SelfPaced_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Notification_get")]
  public static extern int RF21X_QT_Notification_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_Quiz209_get")]
  public static extern int RF21X_QT_Quiz209_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_SendMessage_get")]
  public static extern int RF21X_QT_SendMessage_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21X_QT_UserDefine_get")]
  public static extern int RF21X_QT_UserDefine_get();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_getHidSerialNumber")]
  public static extern global::System.IntPtr getHidSerialNumber();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_messageType_set")]
  public static extern void RF21xMessage_messageType_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_messageType_get")]
  public static extern int RF21xMessage_messageType_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_quizType_set")]
  public static extern void RF21xMessage_quizType_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_quizType_get")]
  public static extern int RF21xMessage_quizType_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_quizNumber_set")]
  public static extern void RF21xMessage_quizNumber_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_quizNumber_get")]
  public static extern int RF21xMessage_quizNumber_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_timeStamp_set")]
  public static extern void RF21xMessage_timeStamp_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_timeStamp_get")]
  public static extern int RF21xMessage_timeStamp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_keypadId_set")]
  public static extern void RF21xMessage_keypadId_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_keypadId_get")]
  public static extern int RF21xMessage_keypadId_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_data_set")]
  public static extern void RF21xMessage_data_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_data_get")]
  public static extern string RF21xMessage_data_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_rawData_set")]
  public static extern void RF21xMessage_rawData_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xMessage_rawData_get")]
  public static extern global::System.IntPtr RF21xMessage_rawData_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_new_RF21xMessage")]
  public static extern global::System.IntPtr new_RF21xMessage();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_delete_RF21xMessage")]
  public static extern void delete_RF21xMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_new_RF21xDevice")]
  public static extern global::System.IntPtr new_RF21xDevice();

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_delete_RF21xDevice")]
  public static extern void delete_RF21xDevice(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_open")]
  public static extern bool RF21xDevice_open(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_close")]
  public static extern bool RF21xDevice_close(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_startQuiz__SWIG_0")]
  public static extern bool RF21xDevice_startQuiz__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_startQuiz__SWIG_1")]
  public static extern bool RF21xDevice_startQuiz__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_startQuiz__SWIG_2")]
  public static extern bool RF21xDevice_startQuiz__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_startQuiz__SWIG_3")]
  public static extern bool RF21xDevice_startQuiz__SWIG_3(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_startDirectly")]
  public static extern bool RF21xDevice_startDirectly(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_stopQuiz")]
  public static extern bool RF21xDevice_stopQuiz(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_setKeypadId")]
  public static extern bool RF21xDevice_setKeypadId(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_GetQuizResult")]
  public static extern byte RF21xDevice_GetQuizResult(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_ClearQuizResult")]
  public static extern void RF21xDevice_ClearQuizResult(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_readDeviceSerialNumber")]
  public static extern bool RF21xDevice_readDeviceSerialNumber(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_writeDeviceSerialNumber")]
  public static extern bool RF21xDevice_writeDeviceSerialNumber(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_resetDeviceSerialNumber")]
  public static extern bool RF21xDevice_resetDeviceSerialNumber(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_checkDeviceSerialNumber")]
  public static extern bool RF21xDevice_checkDeviceSerialNumber(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("rf21x", EntryPoint="CSharp_RF21xDevice_getMessage")]
  public static extern bool RF21xDevice_getMessage(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);
}
