//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class rf21x {
  public static RF21xHidSerialNumbers getHidSerialNumber() {
    RF21xHidSerialNumbers ret = new RF21xHidSerialNumbers(rf21xPINVOKE.getHidSerialNumber(), true);
    return ret;
  }

  public static readonly int RF21X_DT_Unknow = rf21xPINVOKE.RF21X_DT_Unknow_get();
  public static readonly int RF21X_DT_RF217 = rf21xPINVOKE.RF21X_DT_RF217_get();
  public static readonly int RF21X_DT_RF218 = rf21xPINVOKE.RF21X_DT_RF218_get();
  public static readonly int RF21X_DT_RF219 = rf21xPINVOKE.RF21X_DT_RF219_get();
  public static readonly int RF21X_DT_RF215 = rf21xPINVOKE.RF21X_DT_RF215_get();
  public static readonly int RF21X_DT_RF228 = rf21xPINVOKE.RF21X_DT_RF228_get();
  public static readonly int RF21X_MT_Unknow = rf21xPINVOKE.RF21X_MT_Unknow_get();
  public static readonly int RF21X_MT_Teacher = rf21xPINVOKE.RF21X_MT_Teacher_get();
  public static readonly int RF21X_MT_Student = rf21xPINVOKE.RF21X_MT_Student_get();
  public static readonly int RF21X_MT_SetId = rf21xPINVOKE.RF21X_MT_SetId_get();
  public static readonly int RF21X_MT_Auth = rf21xPINVOKE.RF21X_MT_Auth_get();
  public static readonly int RF21X_MT_RecSn = rf21xPINVOKE.RF21X_MT_RecSn_get();
  public static readonly int RF21X_MT_RecVersion = rf21xPINVOKE.RF21X_MT_RecVersion_get();
  public static readonly int RF21X_MT_RecString = rf21xPINVOKE.RF21X_MT_RecString_get();
  public static readonly int RF21X_MT_RecChannel = rf21xPINVOKE.RF21X_MT_RecChannel_get();
  public static readonly int RF21X_MT_RecPower = rf21xPINVOKE.RF21X_MT_RecPower_get();
  public static readonly int RF21X_MT_AllQuResult = rf21xPINVOKE.RF21X_MT_AllQuResult_get();
  public static readonly int RF21X_MT_AllIdResult = rf21xPINVOKE.RF21X_MT_AllIdResult_get();
  public static readonly int RF21X_QT_Homewrok = rf21xPINVOKE.RF21X_QT_Homewrok_get();
  public static readonly int RF21X_QT_Unknow = rf21xPINVOKE.RF21X_QT_Unknow_get();
  public static readonly int RF21X_QT_Rush = rf21xPINVOKE.RF21X_QT_Rush_get();
  public static readonly int RF21X_QT_Single = rf21xPINVOKE.RF21X_QT_Single_get();
  public static readonly int RF21X_QT_Multiple = rf21xPINVOKE.RF21X_QT_Multiple_get();
  public static readonly int RF21X_QT_Number = rf21xPINVOKE.RF21X_QT_Number_get();
  public static readonly int RF21X_QT_Text = rf21xPINVOKE.RF21X_QT_Text_get();
  public static readonly int RF21X_QT_Classify = rf21xPINVOKE.RF21X_QT_Classify_get();
  public static readonly int RF21X_QT_Sort = rf21xPINVOKE.RF21X_QT_Sort_get();
  public static readonly int RF21X_Qt_JudgeOrVote = rf21xPINVOKE.RF21X_Qt_JudgeOrVote_get();
  public static readonly int RF21X_QT_SelectId = rf21xPINVOKE.RF21X_QT_SelectId_get();
  public static readonly int RF21X_QT_Control = rf21xPINVOKE.RF21X_QT_Control_get();
  public static readonly int RF21X_QT_SelfPaced = rf21xPINVOKE.RF21X_QT_SelfPaced_get();
  public static readonly int RF21X_QT_Notification = rf21xPINVOKE.RF21X_QT_Notification_get();
  public static readonly int RF21X_QT_Quiz209 = rf21xPINVOKE.RF21X_QT_Quiz209_get();
  public static readonly int RF21X_QT_SendMessage = rf21xPINVOKE.RF21X_QT_SendMessage_get();
  public static readonly int RF21X_QT_UserDefine = rf21xPINVOKE.RF21X_QT_UserDefine_get();
}
